r7:
	sh recipe7.sh

r6:
	sh recipe6.sh

r5:
	sh recipe5.sh

r4:
	sh recipe4.sh

r3:
	sh recipe3.sh

r2:
	sh recipe2.sh

r1:
	sh recipe1.sh

t: adapter1.txt
	sh -x recipe1.sh

adapter1.txt:
	./devcon listclass net
